# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import base64
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 563)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(863, 542))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setVisible(True)
        self.tableView.horizontalHeader().setStretchLastSection(False)
        self.tableView.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(677, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        pixmap = QtGui.QPixmap()
        file_icon = ("iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAACXBIWXMAAAsTAAALEwEAmpwYAAABE0lEQVR4nO2ZQUrEQBBFnwMG"
                     "PbDoKjhH0IW78TJ6Cp2LDARKArMoZMDprkoqyH9Qm0Cn+pFP0lRACHEN98AeOAITYI11Al6AHUWb/+zY9KU6VEjskzZfJnF0zR+A"
                     "28b15RKTazx0rC9/EuYquv5QIWGJAjfA269r70tLZApQIWHJAqtL2AICq0rYQgIzq0hEBf56De+WfjtFBfyH8LFCwoICz4Fjx+sW"
                     "BCKHwdMWBGbugBH47jiOh0m9WUVPk0A7pifgUIQ6MEXIoQh1YIqQQxHqwBQhhyLUgSlCDkWoA1OEEsfrrQyu39w7zDVznSwG4Mn1"
                     "+8q4aWSuE61xaz/5WurjPI5JITLXaanp3GPM3LwQ/5kfn7GkApTkdIQAAAAASUVORK5CYII=")
        file_icon_data = base64.b64decode(file_icon)
        pixmap.loadFromData(file_icon_data)
        icon = QtGui.QIcon()
        icon.addPixmap(pixmap, QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action.setIcon(icon)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        certificate_icon = ("iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAACXBIWXMAAAsTAAALEwEAmpwYAAABVElEQVR4nO2YUUrDQBCGP"
                       "1DrCQpq4408hyKGHsojWL2BxApWvEq17yOBDSxDQ7Nbm9nKfPC/dJjs/N3dTBhwHKePc2AOLIENICNpA7wBD8CETGbA14hFS4"
                       "9WwGXOP19C8RL0AZylGJgXULQo3acYeFfJL0CVuo2Z68yCFirWpDz4RyUfoni2vBiqKFap2HfKg/X2HYpd62TX8e8MyEjSuAH"
                       "xHcDmCFldao0b6PAdKP0ISWl9QOMG8B3A+4B4I0tH/FMisO/7up3t1NF8aejcR6z6QMwV8Jk59xFrA5MdxXfqm/uYG6j3nPuI"
                       "9SVeqryncKSGzn3E2oCeL7WFp8x9xNrAOsHAukQDjcpbBBNt8c8q9jqmgT5p7hJyb0s0cLrlIm9TA5yUaKBlOiBvOnBdEwP8Y"
                       "Z4ZuQaKwQ1YEzerOihucsXTNbHr6LcL4PFYDNxkxhyOgV+Dgfp9D82TEgAAAABJRU5ErkJggg==")
        certificate_icon_data = base64.b64decode(certificate_icon)
        pixmap.loadFromData(certificate_icon_data)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(pixmap, QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_2.setIcon(icon1)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        setting_icon = ("iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAACXBIWXMAAAsTAAALEwEAmpwYAAADhUlEQVR4nO2Zy0tUURzHP"
                        "2mmqQVZmD1ALBdli3SdofkXFAWV2qZdZWWLiJZFrXxlUrRr5aNN9FhV28pNaKaBWNFrYW5MNDJTMg78Jn4czty5584oI80XDg"
                        "z397xnzu91LmSQQQapQh5wFugB3gATwC9ZE/KsR3gMb9qhFVgMuVpIQ7z0eIEXpCE+KwcbgFJgraxSeRajG960QjbwW5z7E+e"
                        "M5wltUXiNzLKiKIC2X+3u+wC+D4qvOqItb5id6hOjo8ApoEDRNwNDyrFbAbruKL7XQLGiFYjuUaH3pupfuuEIwkngnrzYlHr+"
                        "EygL0LUTmFX8U+Jon+i07bQn6/wRj8wyDxwNofM4sOCh91BU5zdJAYopMmmyCRhzGDFFqsZDd43ILFprTApdv3o2DmyM8gI3l"
                        "ZIZ+ftj2AscAxqBSqKjEjgh/4rRGUO52IzZ7/BVvN06qya4lhtnrNja6iN8XQl/AXI8ZPfIjo0AP2SNSEBWeOhZA3xVflwNK5"
                        "gFfFKCzR4GuxIEqKF1emxIs5L9CKwKI1RmGb0L5Idw/plHZnka4iXyxbaWC0rR/5ALDFiCpuiUBMh0Wfz3JdMUyKoFHlg85p+"
                        "IhxKxqfkHZKNCYR3Q7VCQE+fM62NzMUDvJes4VTh4jI1By7bxZT0RcBKYU4pOO3g6rJ1PhEeKv81Bb1L0OfEhKTRbxczGW0UP"
                        "U8wOKP5hB10XsXOkAEVK4XcHfVrRC0Mezxj/tIOue6sNKfB/5b/AhQSj4Iiim2yTCHUeR+h8ss7bQexqKdoV3aTKRHis+FsTt"
                        "BCRg3i9I42+AlY7eCusNGpSZTxcttrvXXHS6EAyaTTXkYcHZfKKh06L/6Fkm0JZddbOJxpWSpIpZFFaiRxpD8K2Ek+WspXIit"
                        "jM5cg/EdTMzcvOL2kzZ3DNaqdD9yASE22SYWZkDUvA7k6inb7iIcs2a6BxtRBLjSZroNniq0AH5oyMeXoUrJdxsCoJJ6tER70"
                        "1mpbLIBQm4OPCDNLflJJ+GbjfpWCor/Uc6ouIiMMemWVBhvNEaPC8VjlIktDtcmxNyl1/r9W7mLjZEaCr3HGx1SPLdbHlare9"
                        "kS2OxrtaLLaKzu2QV4umOC7L1WIMQZ1hdYTL3X0Rbf2/1+s+HzgapeznyyqTZ2n7gQOZFcJmluekIVpW+ke+PClC3fLBY1xS5"
                        "qz8Hkr3z6wZZMAKxF+x3w7NoGR4dgAAAABJRU5ErkJggg==")
        setting_icon_data = base64.b64decode(setting_icon)
        pixmap.loadFromData(setting_icon_data)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(pixmap, QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_3.setIcon(icon2)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.action_3)
        self.menu_2.addAction(self.action)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KinDownloader"))
        self.pushButton.setText(_translate("MainWindow", "Обзор..."))
        self.pushButton_3.setText(_translate("MainWindow", "Очистить"))
        self.pushButton_2.setText(_translate("MainWindow", "Скачать"))
        self.menu.setTitle(_translate("MainWindow", "Управление"))
        self.menu_2.setTitle(_translate("MainWindow", "Справка"))
        self.action.setText(_translate("MainWindow", "Лог файл"))
        self.action_2.setText(_translate("MainWindow", "О программе"))
        self.action_3.setText(_translate("MainWindow", "Настройки"))
